dist: bionic
jobs:
  include:
    - services:
        - docker
      script:
        - cd backend && docker build .

    - language: cpp
      sudo: required
      compiler:
        - clang
      before_install:
        - sudo apt update
        - sudo apt install -y libopencv-dev
      install:
        - echo $LANG
        - echo $LC_ALL
        - chmod +x ./face/ci_dependencies.sh && ./face/ci_dependencies.sh
      script:
        - echo "=====Building FaceRecognizer====="
        - cd ./face/FaceRecognizer && mkdir build && cd build
        - cmake .. -DSeetaFace_DIR=/home/travis/build/panpaul/SmartLocker/face/SeetaFace2/build/install/lib/cmake
        - make
        - echo "=====Finished====="
        - cd ../../../
        - echo "=====Building RaspberryAgent====="
        - cd ./face/RaspberryAgent && mkdir build && cd build
        - cmake .. -Dncnn_DIR=/home/travis/build/panpaul/SmartLocker/face/ncnn/build/install/lib/cmake/ncnn -Dnlohmann_json_DIR=/home/travis/build/panpaul/SmartLocker/face/json/build/install/lib/cmake/nlohmann_json
        - make
        - echo "=====Finished====="
