dist: bionic
services:
  - docker
env: GO111MODULE=on
before_script: go mod tidy
script:
  - cd backend && docker build .
  
jobs:
  include:
    - language: go
      services:
      - docker
      script:
      - cd backend && docker build .

    - language: cpp
      sudo: required
      compiler:
      - clang
      before_install:
      - apt update && apt upgrade -y
      - apt install -y libopencv-dev
      install:
      - echo $LANG
      - echo $LC_ALL
      - ./face/dependencies.sh
      script:
      - cd ./face/FaceRecognizer && mkdir build && cd build
      - cmake ..
      - make
