WebServer:
  Address: 0.0.0.0
  Port: 7070
  JwtSecret: secret
Database:
  Type: mysql
  Address: 127.0.0.1
  Port: 3306
  User: SmartLocker
  Password: SmartLocker
  Database: smartlocker
  Prefix: sl_
Redis:
  Host: 192.168.99.101:6379
  Password:
Mode: debug