WebServer:
  Address: 0.0.0.0
  Port: 7070
  JwtSecret: secret
Database:
  Type: sqlite
  Address:
  Port:
  User:
  Password:
  Database: SmartLocker.db
  Prefix: sl_
Redis:
  Host: 127.0.0.1:6379
  Password:
Mode: debug